[[pages]]
path = "VBCpages/1_ACB.py"
name = "Liga ACB"
icon = "ğŸ‡ªğŸ‡¸"
[[pages]]
path = "VBCpages/2_Eurocup.py"
name = "Eurocup"
icon = "ğŸŒ"
[[pages]]
path = "VBCpages/3_Euroleague.py"
name = "Euroleague"
icon = "ğŸŒ"
[[pages]]
path = "VBCpages/4_Saporta.py"
name = "Copa Saporta"
icon = "ğŸŒ"
[[pages]]
path = "VBCpages/5_CopaDelRey.py"
name = "Copa del Rey"
icon = "ğŸ‡ªğŸ‡¸"